["protostar.config"]
protostar_version = "0.6.0"

["protostar.project"]
libs_path = "lib"

["protostar.build"]
cairo-path = [
  "lib/cairo_contracts/src"
]

["protostar.test"]
cairo-path = [
  "lib/cairo_contracts/src"
]

["protostar.contracts"]
Zaros=["contracts/liquidity/zaros/Zaros.cairo"]
