["protostar.config"]
protostar_version = "0.6.0"

["protostar.project"]
libs_path = "lib"

["protostar.build"]
cairo-path = [
  "lib/cairo_contracts/src"
]

["protostar.test"]
cairo-path = [
  "lib/cairo_contracts/src"
]

["protostar.contracts"]
Zaros=["contracts/zaros/Zaros.cairo"]
VaultsManager=["contracts/vaults/VaultsManager.cairo"]
ERC20Mintable=["lib/cairo_contracts/src/openzeppelin/token/erc20/presets/ERC20Mintable.cairo"]
MockedOracle=["contracts/oracle/MockedOracle.cairo"]
