["protostar.config"]
protostar_version = "0.6.0"

["protostar.project"]
libs_path = "lib"

["protostar.build"]
cairo-path = [
  "lib/cairo_contracts/src"
]

["protostar.test"]
cairo-path = [
  "lib/cairo_contracts/src"
]

["protostar.contracts"]
Zaros=["contracts/zaros/Zaros.cairo"]
ERC20=["lib/cairo_contracts/src/openzeppelin/token/erc20/presets/ERC20.cairo"]
